// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsJkCpK8OSG3nxSB9uCnPOG37-MwBXBE',
    appId: '1:949738287130:web:926ed0576a548796d161a3',
    messagingSenderId: '949738287130',
    projectId: 'tourist-guide-app-21ef8',
    authDomain: 'tourist-guide-app-21ef8.firebaseapp.com',
    storageBucket: 'tourist-guide-app-21ef8.appspot.com',
    measurementId: 'G-WHQGHVBVCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsalaEJwn14kW8Z9f2Ms-rCdoMWmuTzzQ',
    appId: '1:949738287130:android:31991b3c30473c8ad161a3',
    messagingSenderId: '949738287130',
    projectId: 'tourist-guide-app-21ef8',
    storageBucket: 'tourist-guide-app-21ef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClUbjdcBg5bpbXwKVIa7ufiWk2q7-g4Ts',
    appId: '1:949738287130:ios:f2153474269dfbb8d161a3',
    messagingSenderId: '949738287130',
    projectId: 'tourist-guide-app-21ef8',
    storageBucket: 'tourist-guide-app-21ef8.appspot.com',
    androidClientId: '949738287130-recp0kpl3suru9b2o60g7tpv5ota7ire.apps.googleusercontent.com',
    iosClientId: '949738287130-8qrqvqq1kloev2sr5p1qetiejkrllgsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristGuide',
  );

}